### PR TITLE
Apg uag tags

### PR DESCRIPTION
**Pull request by mike-gangl**
update app-pack-gen API

### CODE REVIEW

**Comment by mike-gangl** [comment]
@edwinsarkissian this is your branch- your yaml is not able to be parsed and won't generate documentation (see the failed action above). You'll need to fix this before we can merge this. Also, we need better documentation on what the variables are (descriptions, defaults if not specified)!

**Comment by mike-gangl** [comment]
even after fixing the tabs, the schema is not valid. @edwinsarkissian did you attempt to generate or validate the schema before saying this was done?

**Comment by edwinsarkissian** [comment]
@mike-gangl, there is a confusion on my side on what I should do. I have not done this test before.  I see the error message, and perhaps it is due to a tab.  I don't believe the error is due to parameter type.  All parameter types are string, and I don't believe the type is incorrect.  Please, see a sample API call and the response at the end of this message. For testing, should I follow the instructions at https://github.com/unity-sds/unity-monorepo/blob/main/tests/system-tests/README.md ? 

esarkiss@MT-400356 unity_cloud % curl -X GET https://1gp9st60gd.execute-api.us-west-2.amazonaws.com/dev/ads-acb/mcp-clone \
   -H 'content-type: application/json' \
   -d '{ "clone_url": "https://github.com/unity-sds/unity-example-application", "apg_tag": "0.3.0", "uag_tag": "0.3.0" }' \
   -H 'Authorization:Bearer eyJraWQiOiJsWmw3XC9yYXFVTVRaTHBVMnJ3bm1paXZKSCtpVFlONngxSUhQNndZaU03RT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhNjA1YTU4MS04ZjFhLTRlYWYtYTFlYy1jYzI3NWQ4NDQ2ZWUiLCJjb2duaXRvOmdyb3VwcyI6WyJVbml0eV9WaWV3ZXIiLCJVbml0eS1UZXN0UHJvai1EZXYtVW5pdHlFeGFtcGxlQXBwLUNsb25lciIsIlVuaXR5X0FkbWluIl0sImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy13ZXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtd2VzdC0yX3lhT3czeWoweiIsImNsaWVudF9pZCI6IjQwYzJzMHVsYmhwOWkwZm1hcGgzc3U5amNoIiwib3JpZ2luX2p0aSI6IjhmZjQyMThmLTEyYTAtNGYyOC1hMjQxLTUzNGY3MmQwMWNlMSIsImV2ZW50X2lkIjoiZWFmY2RiOGEtYjY3Ni00MmIzLWI3OTItODc0YmE5ZDY4YmUxIiwidG9rZW5fdXNlIjoiYWNjZXNzIiwic2NvcGUiOiJhd3MuY29nbml0by5zaWduaW4udXNlci5hZG1pbiIsImF1dGhfdGltZSI6MTcyNTk5MTQyNSwiZXhwIjoxNzI1OTk1MDI1LCJpYXQiOjE3MjU5OTE0MjUsImp0aSI6IjhiNDU5ZmJiLTU0MWItNDVhZS1iZmZlLTUwMzc0OWQwYjkyNCIsInVzZXJuYW1lIjoiZXNhcmtpc3MifQ.FAflPHLM0JOzYz8_wUlAhn0CiZiufK9PARLMKXlc34Fc6_quqgZ77JKcja8jCBl56Xmufiiio0qjnQMdeZ8WFK-m3g_3cs0KXtvDIyuCGY4gsPKIfbiXIedvxjXmlht0vV9yc68hIShFeTjTlVcMChxA5jrCG6CeTFFt0nT2bsQvWZpn5QBd6rw620-BrnEwTAmOsS8EMd3YosA9-tBJolWAYPCNFVcy2iG6J-gC0CRCU6vm4ja9uKaYAoJrM1UWgilvf3bkDC9AR9Gl-ztb0tcfQv9T6M_3tX6uOarYGyNAnSpaAMYZ4Jin761eK9eDaHcBeIJPx_3lvG3x-_Sc9w'
{"clone_url": "https://github.com/unity-sds/unity-example-application", "log_group_name": "/aws/lambda/Unity-ADS--MCP-Clone", "apg_tag": "0.3.0", "uag_tag": "0.3.0"}%

**Comment by mike-gangl** [comment]
> Updates were made as planned: parameters in payload, better description of the parameters ...
> 
> The command openapi-generator generate -c openapi.cfg -i app-package.api.yaml passed without any error.

Thanks, in the future please utilize the actual Github 'approve' option on PRs.

**Pull request merged**
