### PR TITLE
feat: conform more closely to OGC Processes API spec

### PR DESCRIPTION
**Pull request by drewm-jpl**
## Purpose
- This PR updates the usage of the OGC Processes API python client to more closely conform to the `OGC API Processes - Part 2: Deploy, Replace, Undeploy` specification. 

## Proposed Changes
- [CHANGE] Usage of the OGC Processes API python client to match client interface updates.

## Issues

- https://github.com/unity-sds/unity-sps/issues/129

## Testing
- SPS was successfully deployed with this version of the OGC API server. Following deployment, the cwl_dag process was deployed using the OGC API and executed multiple times with different inputs. The different inputs were reflected in the DAG run that was triggered by the execution. Job status was polled using the job status endpoint. Executions/jobs were also dismissed and dismissed jobs were verified to have been deleted from the list of OGC jobs as well as from the list of DAG runs. The cwl_dag was also successfully undeployed. This process was also performed using the unity-sds-client integration of this client.

### CODE REVIEW

**Comment by drewm-jpl** [comment]
@mike-gangl This PR is ready for review whenever you have time.

**Review by LucaCinquini — APPROVED** [review]
I have not tested the changes myself, only reviewed the code. If you want a more thorough check maybe Mike or Godwin should review as well.

**Comment by GodwinShen** [comment]
@drewm-jpl I was able to test the changes in your branch but the job completed in a failed state, the final status message I got was "Job 5d57cd23-196c-4702-aec9-c4f53544ca7d completed with status JobStatus.FAILED".  Not sure if that is expected or what, I was running the echo_message.cwl with a different message passed as an input, e.g., 'cwl_args': "{'message': 'Hello Godwin!'}".  I also tried running with the default "https://raw.githubusercontent.com/unity-sds/unity-sps-workflows/main/demos/echo_message.yaml" file and got the same JobStatus.FAILED state.  Not sure if this is an expected result or what, is that supposed to happen?

**Comment by mike-gangl** [comment]
One last thing, we can turn off pre-commit checking of the Markdown files. i don't mind it being opinionated in the code, but changing README/CHANGELOG files for the sake of it isn't terribly useful. Anyone not using that pre-commit hook will probably blast those change in the next set of PRs.

**Comment by mike-gangl** [comment]
One last thing, the checks are failing at the coveralls section because, for some reason, the job gets closed when we re-issue runs with updated changes. i'm not 100% sure why that happens, but we'll look into fixing that in the future,

**Pull request merged**
